title: "All This Blood"

description: "I don't know how we can see anything through all this blood"

# Build settings
markdown: kramdown

exclude: [
    "documentation",
    "node_modules",
    "server",
    "src",
    "webpack.config.js"
]